enum EErrorCode {
  LOGIN_ERROR = 'LOGIN_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  OTHER_ERROR = 'OTHER_ERROR',
  PARAMETERS_ERROR = 'PARAMETERS_ERROR',
  USER_NOT_ACTIVE = 'USER_NOT_ACTIVE',
  REGISTER_ERROR = 'REGISTER_ERROR',
  SMC_ERROR = 'SMC_ERROR',
  METADATA_ERROR = 'METADATA_ERROR',
  WITHDRAW_ERROR = 'WITHDRAW_ERROR',
  TX_ERROR = 'TRANSACTION_ERROR',
  CANNOT_FIND_ERROR = 'CANNOT_FIND_ERROR',
  ITEM_CONSUME_ERROR = 'ITEM_ERROR',
  PVP_ITEM_NOT_USE = 'PVP_ITEM_NOT_USE',
  INPUT_ERROR = 'INPUT_ERROR',
  AMOUNT_ERROR = 'AMOUNT_ERROR',
  TRANSFER_ERROR = 'TRANSFER_ERROR',
  BAD_REQUEST_ERROR = 'BAD_REQUEST_ERROR',
}

export { EErrorCode }
